baseURL = "https://makecloud.dev/"
languageCode = "en-us"
title = "Makecloud Documentation"


[params]
# (Optional, default 6) Set how many table of contents levels to be showed on page.
# Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
# You can also specify this parameter per page in front matter
BookToC = false

